import type { GameEvent } from "./types.js";

export const totalWeeksPerYear = 30;

export const events: GameEvent[] = [
  {
    id: "hogwarts-express",
    weekMin: 1,
    weekMax: 1,
    title: "Хогвартс-экспресс",
    category: "social",
    description:
      "В купе поезда к тебе подсаживается незнаком{g:ый|ая} первокурсни{g:к|ца} по имени {name} и явно нервничает перед распределением.",
    choices: [
      {
        id: "befriend",
        text: "Разговорить {name_acc} и подбодрить перед распределением",
        quality: 0.9,
        goodOutcome: { text: "Вы с {name_ins} отлично поладили и решили держаться вместе.", friendDelta: 1, statDeltas: { charm: 2, loyalty: 1 } },
        badOutcome: { text: "Разговор с {name_ins} не задался — но хотя бы отвлеклись от волнения.", statDeltas: { charm: 1, courage: -1 } },
      },
      {
        id: "ignore",
        text: "Сделать вид, что читаешь книгу, и не вмешиваться",
        quality: 0.3,
        goodOutcome: { text: "Ты спокойно доехал до Хогвартса в тишине.", statDeltas: { intellect: 2, charm: -1 } },
        badOutcome: { text: "{name} реши{g:л|ла}, что ты задавака, и всю дорогу дул{g:ся|ась}.", statDeltas: { charm: -2, ambition: -1 } },
      },
    ],
  },
  {
    id: "quidditch-tryouts",
    weekMin: 3,
    weekMax: 7,
    minYear: 2,
    excludesClub: "quidditch",
    title: "Отбор в квиддичную команду",
    category: "club",
    description:
      "На доске объявлений факультета висит листок: капитан команды по квиддичу набирает новых игроков на открытый отбор сегодня после уроков. Претендентов уже собралось немало.",
    choices: [
      {
        id: "try-out",
        text: "Прийти на отбор и показать себя",
        quality: 0.55,
        statKey: "courage",
        goodOutcome: { text: "Капитан впечатлён твоей уверенностью в воздухе — тебя берут в команду.", joinClub: "quidditch", statDeltas: { courage: 2, charm: 1 } },
        badOutcome: { text: "Ты неплохо держался, но мест в этом году не хватило на всех.", statDeltas: { courage: 1, charm: -1 } },
      },
      {
        id: "skip-tryout",
        text: "Пропустить отбор — не сегодня",
        quality: 0.4,
        goodOutcome: { text: "Свободный вечер пригодился для отдыха.", statDeltas: { intellect: 1 } },
        badOutcome: { text: "Позже ты жалеешь, что не рискнул попробовать.", statDeltas: { ambition: -1 } },
      },
    ],
  },
  {
    id: "gobstones-open-house",
    weekMin: 3,
    weekMax: 8,
    excludesClub: "gobstones",
    title: "День открытых дверей клуба плюй-камней",
    category: "club",
    description:
      "Проходя мимо кабинета, где собирается клуб плюй-камней, ты слышишь дружный смех и звон камней. Кто-то из участников замечает тебя в дверях и машет рукой — заходи, посмотри.",
    choices: [
      {
        id: "join-in",
        text: "Зайти и сыграть пробную партию",
        quality: 0.7,
        statKey: "charm",
        goodOutcome: { text: "Партия прошла весело, и тебя сразу зовут вступить в клуб.", joinClub: "gobstones", statDeltas: { charm: 2, loyalty: 1 } },
        badOutcome: { text: "Партию ты проиграл, но компания всё равно понравилась.", statDeltas: { charm: 1 } },
      },
      {
        id: "walk-on",
        text: "Вежливо улыбнуться и пройти мимо",
        quality: 0.4,
        goodOutcome: { text: "Спешить некуда — можно заглянуть и в другой раз.", statDeltas: { ambition: 1 } },
        badOutcome: { text: "В коридоре потом было немного неловко встречаться взглядом с участниками клуба.", statDeltas: { charm: -1 } },
      },
    ],
  },
  {
    id: "dueling-tryout",
    weekMin: 4,
    weekMax: 9,
    excludesClub: "dueling",
    title: "Смотр в дуэльном клубе",
    category: "club",
    description:
      "Дуэльный клуб проводит открытый смотр для новичков: старшекурсник вызывает всех желающих на короткий тренировочный поединок прямо у входа в зал.",
    choices: [
      {
        id: "spar",
        text: "Принять вызов на пробный поединок",
        quality: 0.55,
        requiresSpell: true,
        spellId: "expelliarmus",
        statKey: "courage",
        goodOutcome: { text: "Поединок вышел зрелищным — тебя приглашают в клуб.", joinClub: "dueling", statDeltas: { courage: 2, ambition: 1 } },
        badOutcome: { text: "Поединок продержался недолго, но старания заметили.", statDeltas: { courage: 1, charm: -1 } },
      },
      {
        id: "watch-only",
        text: "Просто понаблюдать со стороны",
        quality: 0.4,
        goodOutcome: { text: "Наблюдение помогло понять, как строится защита.", statDeltas: { intellect: 1 } },
        badOutcome: { text: "Ты так и не решился выйти вперёд.", statDeltas: { courage: -1 } },
      },
    ],
  },
  {
    id: "first-flying-lesson",
    weekMin: 3,
    weekMax: 4,
    title: "Первый урок полётов",
    category: "random",
    description:
      "Мадам Трюк выстроила класс в два ряда у мётел, лежащих на траве. Команда простая: вытянуть руку над метлой и произнести «Вверх!» твёрдо и уверенно. У соседей мётлы уже подскакивают в руки, а твоя лишь вяло дёргается и падает обратно в траву.",
    choices: [
      {
        id: "focus",
        text: "Ещё раз протянуть руку и повторить команду",
        quality: 0.8,
        statKey: "courage",
        goodOutcome: { text: "Метла послушно взмывает вверх — учитель доволен.", statDeltas: { courage: 3, ambition: 1 } },
        badOutcome: { text: "Метла взлетает слишком резко, и ты чудом удерживаешь равновесие.", statDeltas: { courage: 1, charm: -1 } },
      },
      {
        id: "panic",
        text: "Довериться первому порыву и запрыгнуть на метлу без раздумий",
        quality: 0.2,
        goodOutcome: { text: "Каким-то чудом получилось — но выглядело неуклюже.", statDeltas: { courage: 1, ambition: 1 } },
        badOutcome: { text: "Падение с метлы у всех на виду. Синяки и уязвлённая гордость.", statDeltas: { courage: -2, charm: -1 } },
      },
      {
        id: "watch-others",
        text: "Понаблюдать, как получается у соседей, и повторить их движение руки",
        quality: 0.55,
        goodOutcome: { text: "Подсмотренное движение сработало — метла наконец слушается.", statDeltas: { courage: 2, intellect: 1 } },
        badOutcome: { text: "Метла шевельнулась, но так и не поднялась — время урока почти вышло.", statDeltas: { intellect: 1, courage: -1 } },
      },
    ],
  },
  {
    id: "library-encounter",
    weekMin: 3,
    weekMax: 5,
    minYear: 4,
    title: "Встреча в библиотеке",
    category: "social",
    nameSeedKey: "romance-interest",
    description:
      "В библиотеке ты замечаешь {name_acc} — {g:однокурсника|однокурсницу}, {g:который|которая} явно тебе симпат{g:ичен|ична}, но не решается заговорить.",
    choices: [
      {
        id: "approach",
        text: "Подойти первым и завести разговор о книге",
        quality: 0.75,
        statKey: "charm",
        goodOutcome: { text: "Завязался тёплый разговор с {name_ins}, {g:который|которая} явно был{g:|а} началом чего-то большего.", relationshipDelta: 2, statDeltas: { charm: 1, courage: 1 } },
        badOutcome: { text: "Разговор с {name_ins} вышел неловким, но не безнадёжным.", relationshipDelta: 1, statDeltas: { charm: -1 } },
      },
      {
        id: "note",
        text: "Оставить анонимную записку с комплиментом",
        quality: 0.5,
        goodOutcome: { text: "Записку приняли тепло, хотя автора пока не разгадали.", relationshipDelta: 1, statDeltas: { charm: 1, ambition: 1 } },
        badOutcome: { text: "Записку сочли странной шуткой одногруппников.", statDeltas: { charm: -1, ambition: -1 } },
      },
      {
        id: "avoid",
        text: "Сделать вид, что очень занят учёбой",
        quality: 0.2,
        goodOutcome: { text: "Ты действительно неплохо позанимался.", gradeDelta: { subject: "history", amount: 2 }, statDeltas: { intellect: 1 } },
        badOutcome: { text: "Момент был упущен — общение с {name_ins} так и не состоялось.", relationshipDelta: -1, statDeltas: { charm: -1 } },
      },
    ],
  },
  {
    id: "potions-mistake",
    weekMin: 4,
    weekMax: 6,
    title: "Ошибка на зельеварении",
    category: "academic",
    description:
      "Класс варит Умиротворяющий бальзам — зелье, снимающее тревогу и напряжение. По рецепту на этом этапе нужно убрать котёл с огня и дать ему немного остыть, прежде чем добавлять последний ингредиент. Твой котёл начинает подозрительно шипеть и приобретать неположенный тёмно-фиолетовый оттенок, а профессор Слизнорт уже посматривает в твою сторону.",
    choices: [
      {
        id: "remove-heat",
        text: "Снять котёл с огня и дать зелью немного остыть",
        quality: 0.9,
        goodOutcome: { text: "Ты вовремя среагировал, зелье почти спасено.", gradeDelta: { subject: "potions", amount: 6 }, statDeltas: { intellect: 1, courage: 1 } },
        badOutcome: { text: "Ты успел снять котёл, но зелье всё равно немного подгорело.", gradeDelta: { subject: "potions", amount: 2 }, statDeltas: { intellect: 1 } },
      },
      {
        id: "keep-stirring",
        text: "Продолжить помешивать зелье, не снимая с огня",
        quality: 0.15,
        goodOutcome: { text: "Каким-то чудом зелье стабилизировалось.", gradeDelta: { subject: "potions", amount: 3 }, statDeltas: { courage: 1, ambition: 1 } },
        badOutcome: { text: "Котёл извергает едкий дым на весь класс. Позор и штрафные баллы.", gradeDelta: { subject: "potions", amount: -6 }, statDeltas: { charm: -1, courage: -1 } },
      },
      {
        id: "add-horn",
        text: "На свой страх и риск добавить толчёный рог единорога раньше срока",
        quality: 0.3,
        goodOutcome: { text: "Неожиданно ингредиент стабилизировал зелье раньше срока — риск оправдался.", gradeDelta: { subject: "potions", amount: 5 }, statDeltas: { ambition: 2, courage: 1 } },
        badOutcome: { text: "Зелье резко вскипает и покрывается пеной — явно не то, что должно получиться.", gradeDelta: { subject: "potions", amount: -4 }, statDeltas: { ambition: -1, courage: -1 } },
      },
      {
        id: "ask-professor",
        text: "Поднять руку и попросить профессора подойти",
        quality: 0.6,
        goodOutcome: { text: "Профессор подсказывает верное движение, зелье удаётся спасти сообща.", gradeDelta: { subject: "potions", amount: 4 }, statDeltas: { intellect: 1, loyalty: 1 } },
        badOutcome: { text: "Пока профессор шёл к твоему столу, зелье успело слегка испортиться.", gradeDelta: { subject: "potions", amount: 1 }, statDeltas: { charm: -1 } },
      },
    ],
  },
  {
    id: "extra-broom-practice",
    weekMin: 5,
    weekMax: 7,
    title: "Лишний час на метле",
    category: "random",
    description:
      "Тренировочное поле опустело, и метла так и просится обратно в воздух. Но комендантский час совсем скоро, а мадам Трюк уже гасит факелы у выхода с площадки.",
    choices: [
      {
        id: "wrap-up",
        text: "Вернуться в замок вовремя",
        quality: 0.7,
        goodOutcome: { text: "Ты успел вернуться до отбоя — и всё равно неплохо потренировался.", statDeltas: { courage: 1, loyalty: 1 } },
        badOutcome: { text: "Мадам Трюк всё равно застала тебя у выхода и слегка отчитала за медлительность.", statDeltas: { charm: -1, ambition: -1 } },
      },
      {
        id: "keep-flying",
        text: "Остаться в воздухе ещё немного",
        quality: 0.35,
        goodOutcome: { text: "Несколько лишних кругов над полем — и мастерство заметно выросло.", statDeltas: { courage: 3, loyalty: -1 } },
        badOutcome: { text: "Тебя застали за нарушением комендантского часа.", statDeltas: { courage: -1, charm: -1 }, housePointsDelta: -3 },
      },
    ],
  },
  {
    id: "friend-conflict",
    weekMin: 6,
    weekMax: 8,
    title: "Ссора с другом",
    category: "social",
    description:
      "На перемене ты пошутил шутку про друга, но заметил, что он, кажется, обиделся на неё. Он смотрит на тебя недовольно, а в глазах таится обида — и весь оставшийся урок демонстративно молчит.",
    choices: [
      {
        id: "apologize",
        text: "Извиниться лично и объяснить, что не хотел обидеть",
        quality: 0.85,
        statKey: "loyalty",
        goodOutcome: { text: "Друг оценил искренность извинений, и вы помирились.", friendDelta: 1, statDeltas: { loyalty: 1, charm: 1 } },
        badOutcome: { text: "Извинения приняты, но осадок остался.", friendDelta: 0, statDeltas: { loyalty: 1, charm: -1 } },
      },
      {
        id: "ignore-conflict",
        text: "Подождать, пока само рассосётся",
        quality: 0.25,
        goodOutcome: { text: "Со временем всё действительно забылось.", friendDelta: 0, statDeltas: { ambition: 1 } },
        badOutcome: { text: "Дружба дала трещину — друг стал более отстранённым.", friendDelta: -1, statDeltas: { loyalty: -1, charm: -1 } },
      },
    ],
  },
  {
    id: "astronomy-tower-night",
    weekMin: 7,
    weekMax: 9,
    title: "Ночное наблюдение",
    category: "academic",
    description:
      "Профессор Синистра задала классу зарисовать положение Марса и двух ближайших созвездий за два часа наблюдений. Ветер треплет страницы, телескоп то и дело сбивается с наводки, а звёздная карта в руках выглядит куда запутаннее, чем на уроке.",
    choices: [
      {
        id: "study-chart",
        text: "Сверяться с картой при каждой записи",
        quality: 0.8,
        goodOutcome: { text: "Наблюдения получились точными и подробными.", gradeDelta: { subject: "astronomy", amount: 5 }, statDeltas: { intellect: 1, ambition: 1 } },
        badOutcome: { text: "Пара облаков помешала, но записи всё же неплохие.", gradeDelta: { subject: "astronomy", amount: 2 }, statDeltas: { intellect: 1 } },
      },
      {
        id: "guess",
        text: "Заполнить наблюдения по памяти, ориентируясь на прошлые занятия",
        quality: 0.2,
        goodOutcome: { text: "На удивление, догадки оказались близки к истине.", gradeDelta: { subject: "astronomy", amount: 1 }, statDeltas: { ambition: 1 } },
        badOutcome: { text: "Профессор сразу заметил ошибки в отчёте.", gradeDelta: { subject: "astronomy", amount: -4 }, statDeltas: { intellect: -1, charm: -1 } },
      },
      {
        id: "ask-neighbor",
        text: "Тихо свериться с записями соседа по телескопу",
        quality: 0.45,
        goodOutcome: { text: "Записи неплохо совпали — вдвоём разобраться оказалось проще.", gradeDelta: { subject: "astronomy", amount: 3 }, friendDelta: 1, statDeltas: { charm: 1 } },
        badOutcome: { text: "Профессор заметила подозрительно похожие отчёты у вас двоих.", gradeDelta: { subject: "astronomy", amount: -2 }, statDeltas: { charm: -1, ambition: -1 } },
      },
    ],
  },
  {
    id: "devils-snare-greenhouse",
    weekMin: 8,
    weekMax: 10,
    title: "Дьявольские силки в теплице",
    category: "academic",
    description:
      "Профессор Стебль показывает классу дьявольские силки — растение, которое душит всё, что к нему прикасается, и боится только света и тепла. Практическое занятие пошло не по плану: росток вырвался из горшка и обвил руку соседа по парте, который уже начинает паниковать.",
    choices: [
      {
        id: "calm-and-light",
        text: "Применить против силков свет и тепло",
        quality: 0.9,
        goodOutcome: { text: "Растение отпустило руку, профессор похвалил твою реакцию.", gradeDelta: { subject: "herbology", amount: 6 }, statDeltas: { courage: 1, intellect: 1 } },
        badOutcome: { text: "Получилось не с первого раза, но всё обошлось.", gradeDelta: { subject: "herbology", amount: 2 }, statDeltas: { courage: 1 } },
      },
      {
        id: "pull",
        text: "Попытаться силой оторвать растение",
        quality: 0.15,
        goodOutcome: { text: "Каким-то образом это сработало, хотя и выглядело рискованно.", gradeDelta: { subject: "herbology", amount: 1 }, statDeltas: { courage: 1, intellect: -1 } },
        badOutcome: { text: "Силки только сильнее сжались — пришлось звать на помощь профессора.", gradeDelta: { subject: "herbology", amount: -5 }, statDeltas: { courage: -1, charm: -1 } },
      },
      {
        id: "call-professor",
        text: "Громко позвать профессора Стебль на помощь",
        quality: 0.55,
        goodOutcome: { text: "Профессор оказалась рядом почти сразу и разобралась с силками сама.", gradeDelta: { subject: "herbology", amount: 3 }, statDeltas: { loyalty: 1 } },
        badOutcome: { text: "Пока профессор шла через теплицу, силки успели напугать полкласса.", gradeDelta: { subject: "herbology", amount: -1 }, statDeltas: { charm: -1, courage: -1 } },
      },
    ],
  },
  {
    id: "spell-practice-corridor",
    weekMin: 9,
    weekMax: 11,
    title: "Тренировка заклинания в коридоре",
    category: "academic",
    description: "У тебя есть немного свободного времени, чтобы отработать движение палочкой перед завтрашним уроком.",
    choices: [
      {
        id: "cast-spell",
        text: "Нарисовать движение палочкой и произнести заклинание",
        quality: 0.6,
        requiresSpell: true,
        spellId: "wingardium",
        goodOutcome: { text: "Заклинание сработало чётко — это точно заметят на следующем уроке.", gradeDelta: { subject: "charms", amount: 6 }, statDeltas: { intellect: 1, ambition: 1 } },
        badOutcome: { text: "Заклинание сработало не с первого раза, но опыт есть опыт.", gradeDelta: { subject: "charms", amount: 1 }, statDeltas: { intellect: 1, courage: -1 } },
      },
      {
        id: "skip",
        text: "Решить, что и так справишься на уроке",
        quality: 0.2,
        goodOutcome: { text: "На уроке всё же удалось выкрутиться.", gradeDelta: { subject: "charms", amount: 1 }, statDeltas: { ambition: 1 } },
        badOutcome: { text: "На уроке ты растерялся без подготовки.", gradeDelta: { subject: "charms", amount: -3 }, statDeltas: { intellect: -1, charm: -1 } },
      },
    ],
  },
  {
    id: "house-cup-points",
    weekMin: 10,
    weekMax: 12,
    title: "Шанс заработать баллы факультету",
    category: "random",
    description:
      "После ужина староста обходит гостиную и просит добровольца помочь с организацией межфакультетского мероприятия — украсить зал, расставить столы и встретить гостей из других факультетов. Работы много, а желающих откликнуться пока не видно.",
    choices: [
      {
        id: "volunteer",
        text: "Вызваться добровольцем",
        quality: 0.75,
        statKey: "loyalty",
        goodOutcome: { text: "Мероприятие прошло отлично — факультет получил баллы.", housePointsDelta: 10, statDeltas: { loyalty: 2, charm: 1 } },
        badOutcome: { text: "Что-то пошло не так, но твои старания оценили.", housePointsDelta: 3, statDeltas: { loyalty: 1 } },
      },
      {
        id: "decline",
        text: "Отказаться — слишком много других дел",
        quality: 0.4,
        goodOutcome: { text: "Ты успел доделать домашние задания.", gradeDelta: { subject: "history", amount: 2 }, statDeltas: { ambition: 1 } },
        badOutcome: { text: "Староста выглядел разочарованным твоим отказом.", statDeltas: { loyalty: -1, charm: -1 } },
      },
    ],
  },
  {
    id: "history-essay",
    weekMin: 11,
    weekMax: 13,
    title: "Эссе по истории магии",
    category: "academic",
    description:
      "Профессор Бинс монотонным голосом задал классу эссе на три свитка пергамента о восстаниях гоблинов — том самом периоде, где даты и имена путаются между собой особенно легко. Срок сдачи уже совсем близко.",
    choices: [
      {
        id: "research",
        text: "Изучить материал в библиотеке заранее",
        quality: 0.85,
        goodOutcome: { text: "Эссе получилось глубоким и обстоятельным.", gradeDelta: { subject: "history", amount: 7 }, statDeltas: { intellect: 2, ambition: 1 } },
        badOutcome: { text: "Материала было много, и часть аргументов вышла слабее.", gradeDelta: { subject: "history", amount: 3 }, statDeltas: { intellect: 1 } },
      },
      {
        id: "last-minute",
        text: "Написать в последнюю ночь перед сдачей",
        quality: 0.25,
        goodOutcome: { text: "Неожиданно получилось связно, несмотря на спешку.", gradeDelta: { subject: "history", amount: 2 }, statDeltas: { ambition: 1, courage: -1 } },
        badOutcome: { text: "Эссе вышло сумбурным, профессор это заметил.", gradeDelta: { subject: "history", amount: -4 }, statDeltas: { intellect: -1, ambition: -1 } },
      },
    ],
  },
  {
    id: "dueling-challenge",
    weekMin: 12,
    weekMax: 14,
    title: "Вызов в дуэльном клубе",
    category: "club",
    description:
      "Один из старшекурсников выходит на середину зала и, усмехнувшись, вызывает тебя на дружеский поединок перед всем клубом. Остальные участники уже расступаются, освобождая место, и явно ждут представления.",
    choices: [
      {
        id: "accept-focused",
        text: "Принять вызов, применив заклинание защиты, которое отрабатывал",
        quality: 0.8,
        requiresSpell: true,
        spellId: "expelliarmus",
        statKey: "courage",
        goodOutcome: { text: "Ты продержался достойно и заслужил уважение клуба.", statDeltas: { courage: 3, charm: 1, ambition: 1 } },
        badOutcome: { text: "Проиграл, но постоял за себя с честью.", statDeltas: { courage: 1, charm: -1 } },
      },
      {
        id: "decline-duel",
        text: "Вежливо отказаться от поединка",
        quality: 0.35,
        goodOutcome: { text: "Никто не осудил осторожность.", statDeltas: { intellect: 1, ambition: -1 } },
        badOutcome: { text: "Кое-кто из клуба посчитал тебя трусоватым.", statDeltas: { courage: -1, charm: -1 } },
      },
    ],
  },
  {
    id: "pet-trouble",
    weekMin: 13,
    weekMax: 15,
    title: "Питомец попал в переделку",
    category: "random",
    description: "Твой питомец пропал на весь день и находится в компании подозрительно довольного Пивза.",
    choices: [
      {
        id: "search-carefully",
        text: "Обойти замок по кругу, начиная с ближайших коридоров",
        quality: 0.8,
        goodOutcome: { text: "Питомец найден целым и невредимым, только немного взъерошенным.", statDeltas: { intellect: 1, loyalty: 1 } },
        badOutcome: { text: "Питомца нашли, но пришлось долго уговаривать Пивза его отпустить.", statDeltas: { charm: -1, intellect: 1 } },
      },
      {
        id: "panic-search",
        text: "Громко звать питомца по имени на бегу",
        quality: 0.3,
        goodOutcome: { text: "Шум привлёк внимание кого-то, кто видел питомца, и его быстро нашли.", statDeltas: { courage: 1, charm: -1 } },
        badOutcome: { text: "Профессор МакГонагалл отчитала тебя за беготню по коридорам.", statDeltas: { charm: -2, ambition: -1 } },
      },
    ],
  },
  {
    id: "hogsmeade-rumor",
    weekMin: 14,
    weekMax: 16,
    title: "Слух из Хогсмида",
    category: "social",
    description:
      "За завтраком ты слышишь, как за соседним столом шёпотом пересказывают неприятную историю про твоего друга — явно приукрашенную, но уже разлетевшуюся по школе. Часть однокурсников поглядывает на него косо, а сам он ещё ничего не знает.",
    choices: [
      {
        id: "defend",
        text: "Публично встать на защиту друга",
        quality: 0.85,
        statKey: "loyalty",
        goodOutcome: { text: "Слух быстро развеялся, а дружба стала крепче.", friendDelta: 2, statDeltas: { loyalty: 2, courage: 1 } },
        badOutcome: { text: "Слух утих не до конца, но друг благодарен за поддержку.", friendDelta: 1, statDeltas: { loyalty: 1, charm: -1 } },
      },
      {
        id: "stay-neutral",
        text: "Не вмешиваться, чтобы не портить отношения с другими",
        quality: 0.25,
        goodOutcome: { text: "Слух сам постепенно затих.", statDeltas: { ambition: 1, loyalty: -1 } },
        badOutcome: { text: "Друг обиделся, что ты промолчал.", friendDelta: -2, statDeltas: { loyalty: -1 } },
      },
    ],
  },
  {
    id: "transfiguration-exam-prep",
    weekMin: 15,
    weekMax: 17,
    title: "Сложное упражнение по трансфигурации",
    category: "academic",
    description:
      "Профессор МакГонагалл раздала классу по спичке: нужно превратить её в иголку — задание, которое пока не даётся половине курса. У кого-то спичка покрывается серебром, у кого-то только тлеет. Твоя пока выглядит как обычная спичка, и время урока уже поджимает.",
    choices: [
      {
        id: "visualize",
        text: "Представить итоговый результат перед произнесением заклинания",
        quality: 0.85,
        goodOutcome: { text: "Спичка превращается в идеальную иголку с первого раза.", gradeDelta: { subject: "transfiguration", amount: 7 }, statDeltas: { intellect: 2, ambition: 1 } },
        badOutcome: { text: "Иголка получилась чуть кривой, но вполне рабочей.", gradeDelta: { subject: "transfiguration", amount: 3 }, statDeltas: { intellect: 1 } },
      },
      {
        id: "brute-force",
        text: "Просто повторять заклинание снова и снова",
        quality: 0.3,
        goodOutcome: { text: "На пятый раз почти получилось.", gradeDelta: { subject: "transfiguration", amount: 2 }, statDeltas: { ambition: 1, intellect: -1 } },
        badOutcome: { text: "Спичка так и осталась спичкой, только обгоревшей.", gradeDelta: { subject: "transfiguration", amount: -3 }, statDeltas: { intellect: -1, charm: -1 } },
      },
      {
        id: "check-textbook",
        text: "Сверить движение палочки с учебником прямо на парте",
        quality: 0.6,
        goodOutcome: { text: "Пропущенная деталь движения нашлась в сносках — спичка меняется на глазах.", gradeDelta: { subject: "transfiguration", amount: 5 }, statDeltas: { intellect: 1, courage: 1 } },
        badOutcome: { text: "Пока листал учебник, почти не осталось времени на попытки.", gradeDelta: { subject: "transfiguration", amount: 1 }, statDeltas: { intellect: 1, ambition: -1 } },
      },
    ],
  },
  {
    id: "reparo-mishap",
    weekMin: 16,
    weekMax: 18,
    title: "Разбитый флакон",
    category: "academic",
    description:
      "На уроке чар твой локоть задевает флакон с драгоценной эссенцией, который профессор Флитвик только что поставил на стол для демонстрации. Флакон падает и со звоном разлетается на осколки прямо у всех на виду.",
    choices: [
      {
        id: "reparo",
        text: "Уверенно нарисовать движение палочкой и произнести Репаро",
        quality: 0.9,
        requiresSpell: true,
        spellId: "reparo",
        statKey: "intellect",
        goodOutcome: { text: "Флакон мгновенно собирается воедино, будто и не разбивался — профессор впечатлён.", gradeDelta: { subject: "charms", amount: 8 }, statDeltas: { intellect: 1, charm: 1 } },
        badOutcome: { text: "Получилось не с первой попытки, но осколки всё же срослись.", gradeDelta: { subject: "charms", amount: 3 }, statDeltas: { intellect: 1 } },
      },
      {
        id: "sweep-up",
        text: "Быстро собрать осколки руками, пока никто не заметил",
        quality: 0.15,
        goodOutcome: { text: "Осколки собраны, но флакон уже не восстановить.", gradeDelta: { subject: "charms", amount: -2 }, statDeltas: { charm: -1 } },
        badOutcome: { text: "Ты порезался о стекло, и профессор всё равно всё заметил.", gradeDelta: { subject: "charms", amount: -5 }, statDeltas: { charm: -1, courage: -1 } },
      },
      {
        id: "ask-help",
        text: "Признаться профессору и попросить помощи",
        quality: 0.55,
        goodOutcome: { text: "Профессор оценил честность и помог восстановить флакон совместно.", gradeDelta: { subject: "charms", amount: 4 }, statDeltas: { loyalty: 1 } },
        badOutcome: { text: "Признание приняли благосклонно, хотя флакон всё равно немного повреждён.", gradeDelta: { subject: "charms", amount: 1 }, statDeltas: { loyalty: 1, charm: -1 } },
      },
    ],
  },
  {
    id: "tutoring-offer",
    weekMin: 17,
    weekMax: 19,
    title: "Просьба подтянуть отстающих",
    category: "social",
    description:
      "Староста замечает, что зельеварение даётся тебе куда легче, чем половине курса, и просит позаниматься по вечерам с младшекурсниками, которые не успевают за программой.",
    choices: [
      {
        id: "accept-job",
        text: "Согласиться позаниматься по вечерам",
        quality: 0.7,
        goodOutcome: { text: "Объясняя другим, ты и сам разобрался в теме куда глубже.", gradeDelta: { subject: "potions", amount: 5 }, statDeltas: { intellect: 1, loyalty: 1 } },
        badOutcome: { text: "Занятия отняли немало времени от собственной учёбы.", gradeDelta: { subject: "potions", amount: -2 }, statDeltas: { loyalty: 1, ambition: -1 } },
      },
      {
        id: "decline-job",
        text: "Отказаться, чтобы не терять свободное время",
        quality: 0.5,
        goodOutcome: { text: "Свободное время пригодилось для отдыха и учёбы.", statDeltas: { charm: 1, ambition: 1 } },
        badOutcome: { text: "Староста выглядел разочарованным отказом.", statDeltas: { loyalty: -1, charm: -1 } },
      },
    ],
  },
  {
    id: "romance-hogsmeade-invite",
    weekMin: 18,
    weekMax: 20,
    minYear: 4,
    title: "Приглашение в Хогсмид",
    category: "social",
    nameSeedKey: "romance-interest",
    description: "{name} наконец приглашает тебя прогуляться до Хогсмида в выходные.",
    choices: [
      {
        id: "accept-date",
        text: "Согласиться и хорошо провести время",
        quality: 0.8,
        statKey: "charm",
        goodOutcome: { text: "Прогулка с {name_ins} прошла прекрасно, и ваши отношения стали крепче.", relationshipDelta: 3, statDeltas: { charm: 1 } },
        badOutcome: { text: "Прогулка получилась милой, но неловкой местами.", relationshipDelta: 1, statDeltas: { charm: -1 } },
      },
      {
        id: "postpone",
        text: "Вежливо предложить перенести на другой раз",
        quality: 0.4,
        goodOutcome: { text: "Перенос приняли с пониманием.", relationshipDelta: 0, statDeltas: { ambition: 1 } },
        badOutcome: { text: "{name} немного расстрои{g:лся|лась} и ста{g:л|ла} более сдержан{g:|а}.", relationshipDelta: -2, statDeltas: { charm: -1 } },
      },
    ],
  },
  {
    id: "quidditch-match-nerves",
    weekMin: 19,
    weekMax: 21,
    title: "Матч по квиддичу",
    category: "club",
    requiresClub: "quidditch",
    minYear: 2,
    guaranteed: true,
    description: "Трибуны заполнены, судья поднимает мяч в воздух — твой матч начинается прямо сейчас.",
    choices: [
      {
        id: "play-match",
        text: "Сыграть матч",
        quality: 0.6,
        requiresMinigame: true,
        minigameId: "quidditch",
        goodOutcome: { text: "Ты поймал момент точно и сыграл заметную роль в победе.", statDeltas: { courage: 3, charm: 1 }, housePointsDelta: 5, gradeDelta: { subject: "quidditch", amount: 8 } },
        badOutcome: { text: "Момент был упущен, матч прошёл для тебя не лучшим образом.", statDeltas: { courage: -1, charm: -1 }, gradeDelta: { subject: "quidditch", amount: 2 } },
      },
      {
        id: "sit-out",
        text: "Попросить замену на этот матч",
        quality: 0.35,
        goodOutcome: { text: "Команда справилась и без тебя, но тренер это запомнил.", statDeltas: { intellect: 1, ambition: -1 } },
        badOutcome: { text: "Команде пришлось нелегко в неполном составе.", housePointsDelta: -3, statDeltas: { charm: -1, loyalty: -1 } },
      },
    ],
  },
  {
    id: "gobstones-tournament",
    weekMin: 20,
    weekMax: 22,
    title: "Турнир по плюй-камням",
    category: "club",
    requiresClub: "gobstones",
    guaranteed: true,
    description: "Клуб плюй-камней проводит внутренний турнир, и сейчас твоя очередь бросать.",
    choices: [
      {
        id: "play-match",
        text: "Сыграть партию",
        quality: 0.6,
        requiresMinigame: true,
        minigameId: "gobstones",
        goodOutcome: { text: "Точный бросок в нужный момент — соперник впечатлён.", friendDelta: 1, statDeltas: { intellect: 1, charm: 1 } },
        badOutcome: { text: "Момент был выбран не лучшим образом, партия сложилась не в твою пользу.", statDeltas: { charm: -1, ambition: -1 } },
      },
      {
        id: "sit-out",
        text: "Уступить очередь и понаблюдать за игрой со стороны",
        quality: 0.35,
        goodOutcome: { text: "Наблюдение за чужой игрой тоже кое-чему научило.", statDeltas: { intellect: 1, courage: -1 } },
        badOutcome: { text: "В клубе немного удивились такой пассивности.", statDeltas: { charm: -1, ambition: -1 } },
      },
    ],
  },
  {
    id: "friend-secret",
    weekMin: 21,
    weekMax: 23,
    title: "Секрет друга",
    category: "social",
    description:
      "Друг под большим секретом рассказал тебе кое-что личное и взял с тебя обещание молчать. На следующий день к тебе подходит однокурсник и как бы невзначай начинает расспрашивать про друга — слишком настойчиво для случайного любопытства.",
    choices: [
      {
        id: "keep-secret",
        text: "Твёрдо промолчать, что бы ни спрашивали",
        quality: 0.9,
        statKey: "loyalty",
        goodOutcome: { text: "Друг узнал о твоей верности и стал доверять ещё больше.", friendDelta: 2, statDeltas: { loyalty: 2, charm: -1 } },
        badOutcome: { text: "Слухи всё равно немного просочились, но не по твоей вине.", friendDelta: 1, statDeltas: { loyalty: 1 } },
      },
      {
        id: "hint",
        text: "Случайно обронить пару намёков",
        quality: 0.15,
        goodOutcome: { text: "К счастью, никто не сложил намёки воедино.", friendDelta: 0, statDeltas: { charm: 1, loyalty: -1 } },
        badOutcome: { text: "Секрет раскрылся, и друг очень разочарован в тебе.", friendDelta: -3, statDeltas: { loyalty: -2, charm: -1 } },
      },
    ],
  },
  {
    id: "exam-anxiety",
    weekMin: 22,
    weekMax: 24,
    title: "Тревога перед экзаменами",
    category: "academic",
    description:
      "Ты раскладываешь на столе конспекты сразу по семи предметам, и от одного взгляда на эту гору пергаментов начинает сводить живот. До экзаменов остаётся всё меньше времени, а кажется, что ты не помнишь ни строчки.",
    choices: [
      {
        id: "plan-schedule",
        text: "Составить расписание повторения по темам",
        quality: 0.85,
        goodOutcome: { text: "Чёткий план сильно снизил тревогу и помог усвоить материал.", statDeltas: { intellect: 3, ambition: 1 } },
        badOutcome: { text: "План помог лишь частично — материала всё равно много.", statDeltas: { intellect: 1, courage: -1 } },
      },
      {
        id: "cram",
        text: "Пытаться выучить всё в последний момент",
        quality: 0.25,
        goodOutcome: { text: "Кое-что удалось удержать в голове.", statDeltas: { intellect: 1, courage: -1 } },
        badOutcome: { text: "Усталость и стресс только помешали запоминанию.", statDeltas: { intellect: -2, charm: -1 } },
      },
    ],
  },
  {
    id: "rival-taunt",
    weekMin: 23,
    weekMax: 25,
    title: "Насмешки соперника",
    category: "social",
    description:
      "В коридоре между уроками {name} с другого факультета громко, чтобы слышали все вокруг, припоминает твою неудачу на последнем занятии. Вокруг собирается небольшая толпа — кто-то посмеивается, кто-то просто с любопытством ждёт твоей реакции.",
    choices: [
      {
        id: "calm-response",
        text: "Ответить спокойно и с достоинством",
        quality: 0.8,
        statKey: "ambition",
        goodOutcome: { text: "Твоя выдержка впечатлила окружающих больше, чем насмешки {name_gen}.", statDeltas: { charm: 2, ambition: 1 } },
        badOutcome: { text: "Насмешки продолжились, но ты не подал виду.", statDeltas: { ambition: 1, charm: -1 } },
      },
      {
        id: "argue-back",
        text: "Ответить не менее едкой шуткой",
        quality: 0.4,
        goodOutcome: { text: "Публика оценила твою колкость, {name} смути{g:лся|лась}.", statDeltas: { charm: 1, loyalty: -1 } },
        badOutcome: { text: "Перепалка переросла в неприятный конфликт с преподавателем.", statDeltas: { charm: -2, ambition: -1 }, housePointsDelta: -5 },
      },
    ],
  },
  {
    id: "final-charm-showcase",
    weekMin: 24,
    weekMax: 26,
    title: "Показательное выступление по чарам",
    category: "academic",
    description:
      "Профессор Флитвик, стоя на стопке книг, вызывает студентов по одному — продемонстрировать перед классом любое из выученных заклинаний. Все взгляды обращаются к тебе, когда он называет твоё имя.",
    choices: [
      {
        id: "demonstrate",
        text: "Уверенно нарисовать движение палочкой перед всем классом",
        quality: 0.85,
        requiresSpell: true,
        spellId: "lumos",
        goodOutcome: { text: "Заклинание сработало безупречно под аплодисменты класса.", gradeDelta: { subject: "charms", amount: 8 }, statDeltas: { charm: 2, courage: 1 } },
        badOutcome: { text: "Получилось со второй попытки, но результат засчитан.", gradeDelta: { subject: "charms", amount: 3 }, statDeltas: { courage: 1 } },
      },
      {
        id: "pass",
        text: "Попросить пропустить твою очередь",
        quality: 0.2,
        goodOutcome: { text: "Профессор перенёс демонстрацию на потом.", gradeDelta: { subject: "charms", amount: 0 }, statDeltas: { courage: -1, ambition: 1 } },
        badOutcome: { text: "Профессор отметил отсутствие уверенности в оценке.", gradeDelta: { subject: "charms", amount: -3 }, statDeltas: { courage: -1, charm: -1 } },
      },
    ],
  },
  {
    id: "late-night-library",
    weekMin: 25,
    weekMax: 27,
    title: "Ночь перед экзаменами в библиотеке",
    category: "academic",
    description:
      "Мадам Пинс разрешила библиотеке работать допоздна перед экзаменами, и почти все столы заняты сгорбившимися над конспектами студентами. У тебя слипаются глаза, а до конца материала ещё далеко.",
    choices: [
      {
        id: "review-notes",
        text: "Спокойно повторить конспекты лекций по темам",
        quality: 0.9,
        goodOutcome: { text: "Материал улёгся в голове гораздо увереннее.", statDeltas: { intellect: 3, ambition: 1 } },
        badOutcome: { text: "Усталость немного помешала, но повторение того стоило.", statDeltas: { intellect: 1, courage: -1 } },
      },
      {
        id: "energy-drink",
        text: "Выпить крепкий бодрящий отвар и заниматься всю ночь",
        quality: 0.3,
        goodOutcome: { text: "Ты успел повторить намного больше материала.", statDeltas: { intellect: 2, courage: -1 } },
        badOutcome: { text: "Наутро ты еле держишься на ногах от недосыпа.", statDeltas: { intellect: -1, courage: -1 } },
      },
    ],
  },
  {
    id: "house-elf-kindness",
    weekMin: 26,
    weekMax: 28,
    title: "Встреча с домовым эльфом",
    category: "random",
    description:
      "Возвращаясь в гостиную поздним вечером, ты натыкаешься на домового эльфа, который тащит непомерно тяжёлый поднос с грязной посудой. Эльф спотыкается, поднос угрожающе кренится, и тарелки вот-вот с грохотом полетят на каменный пол.",
    choices: [
      {
        id: "help-elf",
        text: "Остановиться и помочь всё собрать",
        quality: 0.85,
        statKey: "loyalty",
        goodOutcome: { text: "Эльф очень благодарен и обещает по-своему отплатить добром.", statDeltas: { loyalty: 2, charm: 1 } },
        badOutcome: { text: "Помощь приняли, но благодарить особо было некому — эльф быстро исчез.", statDeltas: { loyalty: 1, ambition: -1 } },
      },
      {
        id: "walk-past",
        text: "Пройти мимо, чтобы не опоздать на урок",
        quality: 0.3,
        goodOutcome: { text: "На урок ты успел вовремя.", statDeltas: { ambition: 1, loyalty: -1 } },
        badOutcome: { text: "Кто-то видел, как ты равнодушно прошёл мимо, и это подпортило репутацию.", statDeltas: { charm: -1, loyalty: -1 } },
      },
    ],
  },
  {
    id: "pre-exam-pep-talk",
    weekMin: 27,
    weekMax: 29,
    title: "Разговор перед экзаменами",
    category: "social",
    description:
      "Вечером в гостиной друзья собираются в кругу у камина — все немного на нервах перед решающими экзаменами года. Кто-то предлагает обсудить план подготовки вместе, кто-то уже тихо перелистывает конспекты в стороне.",
    choices: [
      {
        id: "support-friends",
        text: "Подбодрить друзей и обсудить план подготовки вместе",
        quality: 0.85,
        goodOutcome: { text: "Общая поддержка укрепила дружбу и снизила общий стресс.", friendDelta: 2, statDeltas: { intellect: 1, charm: 1 } },
        badOutcome: { text: "Разговор помог лишь немного, но настроение стало лучше.", friendDelta: 1, statDeltas: { charm: 1 } },
      },
      {
        id: "study-alone",
        text: "Уйти готовиться в одиночестве",
        quality: 0.4,
        goodOutcome: { text: "Уединение помогло сосредоточиться на материале.", statDeltas: { intellect: 2, charm: -1 } },
        badOutcome: { text: "Друзья восприняли уход как отстранённость.", friendDelta: -1, statDeltas: { charm: -1 } },
      },
    ],
  },
  {
    id: "final-week-nerves",
    weekMin: 29,
    weekMax: 30,
    title: "Последние приготовления",
    category: "academic",
    description:
      "Экзамены начинаются завтра с самого утра. В гостиной ещё горит свет — кто-то нервно бормочет формулы себе под нос, кто-то уже собирает сумку. Ты стоишь перед выбором, как провести последний вечер перед решающим днём.",
    choices: [
      {
        id: "light-review",
        text: "Лёгкое повторение и ранний сон",
        quality: 0.9,
        goodOutcome: { text: "Ты выспался и чувствуешь ясность в голове.", statDeltas: { intellect: 2, courage: 1 } },
        badOutcome: { text: "Сон был не самым крепким, но всё равно лучше, чем ничего.", statDeltas: { intellect: 1, courage: -1 } },
      },
      {
        id: "last-minute-panic",
        text: "Перечитывать всё подряд до поздней ночи",
        quality: 0.2,
        goodOutcome: { text: "Кое-что удалось освежить в памяти в последний момент.", statDeltas: { intellect: 1, courage: -1 } },
        badOutcome: { text: "Ты вымотан и плохо соображаешь с самого утра.", statDeltas: { intellect: -2, courage: -1 } },
      },
    ],
  },
  {
    id: "broom-proficiency-test",
    weekMin: 9,
    weekMax: 12,
    minYear: 2,
    maxYear: 2,
    title: "Экзамен по полётам",
    category: "academic",
    description:
      "На втором курсе мадам Трюк принимает у каждого норматив: пролететь через три горящих обруча над стадионом на скорости, не сбив ни одного. Прошлогодняя неуверенность ещё свежа в памяти, а обручи, если приглядеться, подвешены заметно выше человеческого роста.",
    choices: [
      {
        id: "full-speed",
        text: "Разогнаться и пройти дистанцию на полной скорости",
        quality: 0.65,
        statKey: "courage",
        goodOutcome: { text: "Все три обруча пройдены чисто — мадам Трюк одобрительно кивает и что-то отмечает в свитке.", statDeltas: { courage: 3, ambition: 1 } },
        badOutcome: { text: "Скорость подвела на последнем обруче — задел край, но удержался в воздухе.", statDeltas: { courage: 1, charm: -1 } },
      },
      {
        id: "steady-pace",
        text: "Лететь размеренно, тщательно целясь в каждый обруч",
        quality: 0.85,
        goodOutcome: { text: "Медленно, но безупречно — мадам Трюк хвалит именно точность, а не скорость.", statDeltas: { intellect: 1, courage: 1 } },
        badOutcome: { text: "Излишняя осторожность стоила времени, норматив сдан впритык.", statDeltas: { intellect: 1 } },
      },
    ],
  },
  {
    id: "first-hogsmeade-trip",
    weekMin: 8,
    weekMax: 11,
    minYear: 3,
    maxYear: 3,
    title: "Первая вылазка в Хогсмид",
    category: "social",
    description:
      "С третьего курса ученикам с разрешением от родителей наконец можно выбираться в деревню Хогсмид по выходным — единственное полностью волшебное поселение страны. Толпа однокурсников уже гудит у ворот в предвкушении: витрины со сладостями, шумный трактир, лавка розыгрышей.",
    choices: [
      {
        id: "explore-with-friends",
        text: "Обойти деревню вместе с целой компанией однокурсников",
        quality: 0.8,
        statKey: "charm",
        goodOutcome: { text: "Весёлая прогулка компанией надолго запомнится — от лавки до лавки, от смеха до смеха.", friendDelta: 1, statDeltas: { charm: 2, loyalty: 1 } },
        badOutcome: { text: "В толпе постоянно теряли друг друга, но в итоге всё равно неплохо провели время.", statDeltas: { charm: 1 } },
      },
      {
        id: "explore-alone",
        text: "Улизнуть в одиночку и внимательно изучить каждую лавку",
        quality: 0.5,
        goodOutcome: { text: "Не спеша разглядывая витрины, ты нашёл несколько по-настоящему редких вещей.", statDeltas: { intellect: 1, ambition: 1 } },
        badOutcome: { text: "В одиночку было скучновато — и деревня быстро опустела в сумерках.", statDeltas: { charm: -1 } },
      },
    ],
  },
  {
    id: "winter-ball",
    weekMin: 14,
    weekMax: 17,
    minYear: 4,
    maxYear: 4,
    title: "Зимний бал",
    category: "social",
    description:
      "Большой зал преображён до неузнаваемости: ледяные скульптуры, гирлянды остролиста под потолком, оркестр настраивает инструменты на возвышении. Впервые за много лет Хогвартс устраивает настоящий бал, и всю неделю только и разговоров, что о том, кто кого пригласит.",
    choices: [
      {
        id: "ask-someone",
        text: "Набраться смелости и пригласить того, кто давно нравится",
        quality: 0.7,
        statKey: "courage",
        goodOutcome: { text: "Приглашение принято с улыбкой — весь вечер прошёл как в тумане счастья.", relationshipDelta: 2, statDeltas: { courage: 2, charm: 1 } },
        badOutcome: { text: "Отказ было пережить неловко, но ты хотя бы попробовал.", statDeltas: { courage: 1, charm: -1 } },
      },
      {
        id: "go-with-friends",
        text: "Пойти большой компанией друзей, без пары",
        quality: 0.75,
        goodOutcome: { text: "Танцы до упаду в шумной компании — обошлось без драмы и с кучей смеха.", friendDelta: 1, statDeltas: { charm: 1, loyalty: 1 } },
        badOutcome: { text: "Компания разбрелась по парам почти сразу, и вечер вышел не таким весёлым.", statDeltas: { charm: -1 } },
      },
      {
        id: "skip-ball",
        text: "Остаться в гостиной с книгой — балы не для всех",
        quality: 0.35,
        goodOutcome: { text: "Тихий вечер помог наверстать учёбу, пока Большой зал гремел музыкой.", statDeltas: { intellect: 2 } },
        badOutcome: { text: "На следующий день только и разговоров было, что о бале — и ты почувствовал себя немного в стороне.", statDeltas: { charm: -1, loyalty: -1 } },
      },
    ],
  },
  {
    id: "mock-exams-pressure",
    weekMin: 12,
    weekMax: 15,
    minYear: 5,
    maxYear: 5,
    title: "Пробные экзамены",
    category: "academic",
    description:
      "Пятый курс — переломный: деканы факультетов лично предупредили, что итоговые экзамены этого года будут учитываться при выборе профессии после школы. Чтобы никто не расслаблялся раньше времени, профессора устраивают внеплановые пробные экзамены сразу по всем предметам.",
    choices: [
      {
        id: "study-group",
        text: "Организовать учебную группу с однокурсниками",
        quality: 0.8,
        statKey: "intellect",
        goodOutcome: { text: "Совместные разборы сложных тем оказались куда эффективнее одиночной зубрёжки.", friendDelta: 1, statDeltas: { intellect: 2, loyalty: 1 } },
        badOutcome: { text: "Группа то и дело отвлекалась на разговоры, но что-то полезное всё же осело в памяти.", statDeltas: { intellect: 1 } },
      },
      {
        id: "solo-marathon",
        text: "Готовиться в одиночку без остановки",
        quality: 0.55,
        goodOutcome: { text: "Полная концентрация дала результат — пробные экзамены сданы уверенно.", statDeltas: { intellect: 2, courage: -1 } },
        badOutcome: { text: "Марафон без перерывов вымотал сильнее, чем сами экзамены.", statDeltas: { intellect: 1, courage: -2 } },
      },
    ],
  },
  {
    id: "prefect-consideration",
    weekMin: 20,
    weekMax: 23,
    minYear: 5,
    maxYear: 5,
    title: "Разговор о значке старосты",
    category: "social",
    description:
      "Декан факультета вызывает тебя после урока для короткого разговора: в следующем году факультету понадобятся новые старосты, и твоё имя — в списке кандидатов. Это не обещание значка, но явный знак, что за тобой наблюдают.",
    choices: [
      {
        id: "embrace-responsibility",
        text: "Ответить, что готов(а) взять на себя больше ответственности",
        quality: 0.8,
        statKey: "ambition",
        goodOutcome: { text: "Декан явно доволен ответом — и с этого дня к тебе стали чуть внимательнее прислушиваться.", statDeltas: { ambition: 2, loyalty: 1 } },
        badOutcome: { text: "Ответ был встречен благосклонно, хотя особых перемен пока не заметно.", statDeltas: { ambition: 1 } },
      },
      {
        id: "stay-modest",
        text: "Честно признаться, что пока не уверен(а) в себе",
        quality: 0.5,
        goodOutcome: { text: "Честность оценили — декан пообещал вернуться к разговору позже.", statDeltas: { charm: 1, loyalty: 1 } },
        badOutcome: { text: "Момент был упущен, и разговор больше не поднимался.", statDeltas: { ambition: -1 } },
      },
    ],
  },
  {
    id: "mentor-younger-student",
    weekMin: 6,
    weekMax: 9,
    minYear: 6,
    maxYear: 6,
    title: "Растерянный первокурсник",
    category: "social",
    nameSeedKey: "mentee",
    description:
      "В коридоре ты замечаешь {name_acc} — совсем растерянного первокурсника с картой, которая упрямо не желает разворачиваться в нужную сторону. До начала урока остаётся всего пара минут, а первокурсники факультета явно ещё не выучили короткие пути замка.",
    choices: [
      {
        id: "walk-together",
        text: "Проводить {name_acc} до нужного класса лично",
        quality: 0.85,
        statKey: "loyalty",
        goodOutcome: { text: "{name} рассказал{g:|а} по дороге о доме, а на прощание искренне поблагодарил{g:|а} за помощь.", statDeltas: { loyalty: 2, charm: 1 } },
        badOutcome: { text: "Дорогу до класса нашли, хоть и с опозданием на пару минут.", statDeltas: { loyalty: 1 } },
      },
      {
        id: "point-direction",
        text: "Быстро объяснить дорогу и поспешить на свой урок",
        quality: 0.45,
        goodOutcome: { text: "Объяснение оказалось на удивление понятным — {name} добрался{g:|ась} без проблем.", statDeltas: { intellect: 1 } },
        badOutcome: { text: "Судя по растерянному виду, объяснение не особо помогло.", statDeltas: { charm: -1 } },
      },
    ],
  },
  {
    id: "career-counseling",
    weekMin: 5,
    weekMax: 8,
    minYear: 7,
    maxYear: 7,
    title: "Разговор о будущем",
    category: "academic",
    description:
      "Декан факультета приглашает каждого семикурсника на личную беседу о планах после выпуска. На столе разложены брошюры: курсы целителей, аврорат, министерские курсы, драконологический заповедник — кажется, что выбор придётся делать прямо сейчас, а определённости пока нет.",
    choices: [
      {
        id: "ambitious-plan",
        text: "Уверенно назвать амбициозную профессию мечты",
        quality: 0.75,
        statKey: "ambition",
        goodOutcome: { text: "Декан подробно расписал(а), какие экзамены понадобятся — план внезапно стал реальным.", statDeltas: { ambition: 2, intellect: 1 } },
        badOutcome: { text: "План озвучен, но декан осторожно предупредил(а), что конкурс будет жёстким.", statDeltas: { ambition: 1 } },
      },
      {
        id: "honest-uncertainty",
        text: "Честно признаться, что пока не определился(ась)",
        quality: 0.55,
        goodOutcome: { text: "Декан отнёсся(лась) с пониманием и посоветовал(а) присмотреться к сильным сторонам.", statDeltas: { charm: 1, intellect: 1 } },
        badOutcome: { text: "Неопределённость слегка встревожила декана — время до выпуска утекает быстро.", statDeltas: { ambition: -1 } },
      },
    ],
  },
  {
    id: "final-quidditch-cup",
    weekMin: 24,
    weekMax: 27,
    minYear: 7,
    maxYear: 7,
    requiresClub: "quidditch",
    guaranteed: true,
    title: "Финал Кубка школы по квиддичу",
    category: "club",
    description:
      "Последний матч школьной карьеры. Трибуны забиты до отказа — даже те, кто квиддичем никогда не интересовался, пришли посмотреть на финал. Капитан перед матчем произносит короткую речь о том, что сегодняшний день запомнится на всю жизнь, что бы ни показал итоговый счёт.",
    choices: [
      {
        id: "play-match",
        text: "Сыграть финал во весь свой опыт",
        quality: 0.65,
        requiresMinigame: true,
        minigameId: "quidditch",
        goodOutcome: { text: "Финальный матч школьной карьеры завершился триумфом — трибуны скандируют название факультета.", statDeltas: { courage: 3, charm: 2 }, housePointsDelta: 15, gradeDelta: { subject: "quidditch", amount: 10 } },
        badOutcome: { text: "Финал не задался, но команда сражалась до последней секунды — и это тоже чего-то стоит.", statDeltas: { courage: 1 }, gradeDelta: { subject: "quidditch", amount: 3 } },
      },
      {
        id: "sit-out",
        text: "Признаться тренеру, что не готов(а) сыграть решающий матч",
        quality: 0.2,
        goodOutcome: { text: "Команда справилась без тебя, но этот момент будет мучить ещё долго.", statDeltas: { ambition: -1 } },
        badOutcome: { text: "Команде пришлось нелегко в неполном составе в решающем матче сезона.", housePointsDelta: -5, statDeltas: { charm: -1, loyalty: -1 } },
      },
    ],
  },
];
